version: "3.8"

services:

    web:
        build:
            context: ./docker-bin/webserver
            args:
                UID: ${UID}
                GID: ${GID}
        container_name: '${PROJECT_KEY}-web'
        restart: 'unless-stopped'
        ports:
            - '${HOST_WEB_PORT}:80'
        depends_on:
            - db
        volumes:
            - ./:/var/www/html

    db:
        build:
            context: ./docker-bin/mysql
        container_name: '${PROJECT_KEY}-db'
        restart: 'unless-stopped'
        ports:
            - '${HOST_DB_PORT}:80'
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass123

    pma:
        image: phpmyadmin:5.1
        container_name: '${PROJECT_KEY}-pma'
        restart: 'unless-stopped'
        ports:
            - '${HOST_PMA_PORT}:80'
        environment:
            PMA_HOST: db
            PHP_UPLOAD_MAX_FILESIZE: 67108864

volumes:
    db-data: